source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CocoPodsSam_Example', :exclusive => true do
  pod 'CocoPodsSam', :path => '../'
end

target 'CocoPodsSam_Tests', :exclusive => true do
  pod 'CocoPodsSam', :path => '../'

  
end
